### ISSUE TITLE
How to pass props in createElement 

### ISSUE THREAD

**Issue by jardakotesovec** [devknoll/relay-nested-routes#9]
I have been using createElement on react-router to pass intlData for react-intl. But thats not working anymore with relay-nested-routes. Application does not get these intlData. 

Does it seem like possible bug in relay-nested-routes?

```
function createElement(Component, props) {
    if (Component === Application) {
        return <Component {...props} {...intlData} />
    }
    return <Component {...props} />
}
```

**Comment by taion** [comment]
There's a thought, actually - the current way that `props` forwarding to the `RootContainer` is set up doesn't actually work for `renderFetched`, because the user won't have any access to the `NestedRenderer` class there.

We could solve both that and this current issue by picking up the `renderFetched` prop on the route (if any) and using that to render each of the components in `NestedRenderer`.

**Comment by taion** [comment]
The new API will involve explicitly passing in `createElement` to the `Router`. As needed, you'll be able to wrap that function to inject additional props.

**Comment by taion** [comment]
Although in your example there, the `renderFetched` hook on the route for the `Application` component would probably serve you better than branching on every render there.
